FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy only the producer code
COPY workspace/sp500 /app

# Install only needed packages
RUN pip install --no-cache-dir \
    yfinance \
    kafka-python \
    pandas \
    python-dateutil

# Default command
CMD ["python", "main_producer.py"]
