FROM bitnami/spark:3.5

# Switch to root to install packages
USER root

# Install pip and Python packages
RUN apt-get update && \
    apt-get install -y python3-pip && \
    pip3 install --no-cache-dir \
        pandas \
        python-dotenv \
        kafka-python \
        boto3

# Revenir à l'utilisateur non-root recommandé par Bitnami
USER 1001

# Copier le code
COPY workspace/sp500 /app

# Définir le dossier de travail
WORKDIR /app

# Lancer le consumer
CMD ["python3", "main_consumer.py"]
