FROM bitnami/spark:3.5

# Install Python dependencies
RUN pip install --no-cache-dir \
    boto3 \
    kafka-python \
    pandas \
    pyarrow \
    yfinance \
    python-dateutil

# Copy only necessary files
COPY workspace/sp500 /app
WORKDIR /app

CMD ["python", "main_consumer.py"]
